In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer



In [2]:
df = pd.read_csv("tmdb_5000_credits.csv")
df.reset_index(inplace = True)
df.head()

,index,movie_id,title,cast,crew
0,0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."


In [3]:
df.shape

(4803, 5)

In [4]:
features = ['movie_id' , 'title' , 'cast' , 'crew']
df[features].head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."


In [5]:
df[features].isnull().values.any()

np.False_

In [6]:
def combine_features(row):
    return row['movie_id']+' '+row['title']+' '+row['cast']+' '+row['crew']

In [7]:
count_matrix = CountVectorizer().fit_transform(df['crew'])
cosine_sim = cosine_similarity(count_matrix)
print(cosine_sim)

[[1.         0.95317455 0.98678375 ... 0.90460132 0.72243161 0.83699884]
 [0.95317455 1.         0.95960533 ... 0.94511902 0.74185023 0.87578137]
 [0.98678375 0.95960533 1.         ... 0.92009212 0.7326647  0.84834869]
 ...
 [0.90460132 0.94511902 0.92009212 ... 1.         0.72228544 0.87785039]
 [0.72243161 0.74185023 0.7326647  ... 0.72228544 1.         0.72011904]
 [0.83699884 0.87578137 0.84834869 ... 0.87785039 0.72011904 1.        ]]


In [8]:
cosine_sim.shape

(4803, 4803)

In [9]:
def get_title_from_index(index):
    return df[df.index == index]["title"].values[0]
def get_index_from_title(title):
    return df[df.title == title]["index"].values[0]

In [10]:
movie_user_likes = "Avatar" 
movie_index = get_index_from_title(movie_user_likes)

similar_movies = list(enumerate(cosine_sim[movie_index]))

In [11]:
print(similar_movies)

[(0, np.float64(1.0000000000000087)), (1, np.float64(0.9531745494286907)), (2, np.float64(0.9867837456397707)), (3, np.float64(0.9758809552499962)), (4, np.float64(0.9647425605454233)), (5, np.float64(0.9382994584365597)), (6, np.float64(0.9648312448487268)), (7, np.float64(0.961318643472782)), (8, np.float64(0.9411368226608977)), (9, np.float64(0.9752230196966266)), (10, np.float64(0.9068749466819628)), (11, np.float64(0.9197994525897203)), (12, np.float64(0.9421646707804949)), (13, np.float64(0.9385618401934619)), (14, np.float64(0.9659973199479047)), (15, np.float64(0.9626429326788651)), (16, np.float64(0.9886807501314491)), (17, np.float64(0.9361002021849458)), (18, np.float64(0.9456131957073582)), (19, np.float64(0.9874612079187196)), (20, np.float64(0.9868461423111169)), (21, np.float64(0.9397330402801644)), (22, np.float64(0.9828797832546472)), (23, np.float64(0.9451264485944235)), (24, np.float64(0.964072539227126)), (25, np.float64(0.9525346247267591)), (26, np.float64(0.98173

In [12]:
sorted_similar_movies = sorted(similar_movies , key = lambda x:x[1] , reverse=(True))


In [13]:
i = 0
print("Top 7 similar movies to "+movie_user_likes+" are:\n")
for element in sorted_similar_movies:
    print(get_title_from_index(element[0]))
    i=i+1
    if i>=7:
        break

Top 7 similar movies to Avatar are:

Avatar
The Hunger Games: Mockingjay - Part 1
Ender's Game
Cloud Atlas
Exodus: Gods and Kings
2012
The Avengers
